### ISSUE TITLE
Add lint checks to CI

### ISSUE THREAD

**Issue by ryanjulian** [ryanjulian/rllab#100]
Options:
* pylint
* autopep8
* flake8
* flake8-bugbear
* pyflakes
* pycodestyle
* mypy
* pytype

See:
https://github.com/PyCQA

Important rules (running list):
* PEP8 import styling

**Comment by CatherineSue** [comment]
I find most python imports tools support alphabetical order only with import statements before from X import ... statements. 

Flake8-import-order is the only tool I find that supports the alphabetical order we are using, which ignores 'from' or 'import' or 'as', like [google](https://google.github.io/styleguide/pyguide.html?showone=Imports_formatting#Imports_formatting). But flake8-import-order only prints the flake warnings instead of automatically reordering imports.

Other tools such as isort, autopep8 supports reorder, but they don't support the alphabetical order we are using. My guess is because PEP8 style only enforces groups without enforcing the order within the groups.

**Comment by ryanjulian** [comment]
See https://github.com/rlworkgroup/garage/issues/8
