### ISSUE TITLE
Use rllab mujoco directory for mujoco-py

### ISSUE THREAD

**Issue by zhanpenghe** [ryanjulian/rllab#128]
After upgraded to mujoco-py and mj150, the setup_mujoco.sh, which copy the mj files to vendors, lacks the set up of environment variable LD_LIBRARY_PATH. Users will have to follow the mujoco-py instructions to setup the mujoco-py properly and the vendor folder is not useful.

The goal is to use the vendor folder for rllab instead of ~/.mujoco/mj150/bin .

**Comment by ryanjulian** [comment]
I think this is a step backward not a step forward. Vendoring our dependencies works in a monolithic repo, but not a `pip` package. The custom mujoco setup script is also a crutch and makes setup more complicated. Eventually this all needs to work unattended, and the only way we can guarantee that is assuming that the user uses the standard mujoco setup folder in `.mujoco`

The switch to using the system mujoco was an intentional change made when we upgraded mujoco_py. I think there are ways of forcing python to use the correct LD_LIBRARY_PATH without vendoring the dependency and also without forcing the user to setup an environment variable.

**Comment by zhanpenghe** [comment]
I agree. This issue was originally opened to conform to the previous setup. I think setting the LD_LIBRARY_PATH with python could be a good fix. In this case, we could also cleanup the setup_mujoco.sh.
