### ISSUE TITLE
GymEnv should not show a plot when plot=False

### ISSUE THREAD

**Issue by ryanjulian** [ryanjulian/rllab#31]

**Comment by zhanpenghe** [comment]
I have investigated this before and I think the problem is the video recorder for gym environment. 
`class GymEnv(Env, Serializable):
    def __init__(self, env_name, record_video=True, video_schedule=None, log_dir=None, record_log=True,`

A quick fix could be setting the default value of record_video to False and the plot will not show up.
I am not sure if tensoflow allows recording video without rendering .

**Comment by ryanjulian** [comment]
Hmm sounds good. I think we should preserve the invariant that `record_video=True` will successfully record a video (even if that means ignoring `plot=False`). The ideal is for gym to record off-screen, but I'm not sure that's supported.

**Comment by jonashen** [comment]
I have determined that it is impossible for gym to record off-screen, because the downloaded video is built from a series of static RGB frames, and it retrieves these frames through `frame = 
self.env.render(...)`, and gym's core `render` function by default must draw out the window in order to capture the RGB frame through internal screen capture. 

In short, plot=False cannot produce a recorded video. How should we proceed?

**Comment by ryanjulian** [comment]
I think it's fine to require `plot=True` to guarantee recording.

**Comment by jonashen** [comment]
When plot=False, it will still display the window as well as record. Should we leave that as well, or simply turn off window display (and thus also turn off recording)?

**Comment by ryanjulian** [comment]
IMO the correct behavior is to turn off recording when `plot=False`. It should probably be an enum option rather than 2 booleans which interact, but c'est la vie. 

We will have another opportunity to address this when we replace rllab.Env with gym.Env.

**Comment by ryanjulian** [comment]
See https://github.com/rlworkgroup/garage/issues/43
