### ISSUE TITLE
Support for tensor logging to tensorboard

### ISSUE THREAD

**Issue by ryanjulian** [ryanjulian/rllab#39]

**Comment by CatherineSue** [comment]
The intention for this issue is to support the visualization of a tensor in a scalar. In the scalar, each line corresponds to an element in the tensor.

Tensorboard currently supports the summary operations of `tf.summary.scalar`, `tf.summary.image`, `tf.summary.audio`, `tf.summary.text`, and `tf.summary.histogram`, except for `tf.summary.tensor_summary`. But we can make a custom scalar through the plugin [custom/scalar](https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/custom_scalar).
